# Generated by Django 2.1.7 on 2019-03-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('prep_time', models.TimeField(blank=True)),
                ('cook_time', models.TimeField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=100)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('publication', models.CharField(blank=True, max_length=100)),
                ('page_number', models.SmallIntegerField(blank=True)),
                ('overnight', models.BooleanField(blank=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
