# Generated by Django 2.1.7 on 2019-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_builder', '0002_auto_20190310_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='recipe',
            name='weeknight',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
