# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HikingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('mile', models.DecimalField(decimal_places=1, max_digits=8)),
                ('state', models.CharField(max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('day_off', models.BooleanField()),
                ('precipitation', models.BooleanField()),
                ('precip_status', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
    ]
