# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalachian_trail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikingday',
            name='precip_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
