# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalachian_trail', '0002_auto_20171205_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingday',
            name='trail_magic',
            field=models.BooleanField(default=False),
        ),
    ]
