# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalachian_trail', '0003_hikingday_trail_magic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingday',
            name='resupply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hikingday',
            name='resupply_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
