# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalachian_trail', '0005_auto_20171205_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikingday',
            name='miles_hiked',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
    ]
