# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('athensrock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
