# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('mileage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('location', models.CharField(max_length=255)),
                ('type_of_run', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
    ]
