# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningday',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
