# Generated by Django 3.2.12 on 2022-02-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('spacing', models.IntegerField(blank=True)),
                ('species', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('started', models.DateField(blank=True)),
                ('planting_start_days_to_first_frost', models.IntegerField(blank=True)),
                ('planting_end_days_to_first_frost', models.IntegerField(blank=True)),
                ('planting_depth_in_inches', models.IntegerField(blank=True)),
                ('planting_method', models.CharField(blank=True, max_length=255)),
                ('picture', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
