# Generated by Django 3.2.12 on 2022-03-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0002_seed_staring_soil'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='sub_classification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
