# Generated by Django 3.2.12 on 2022-03-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0003_seed_sub_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='staring_soil',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='started',
        ),
    ]
