# Generated by Django 3.2.12 on 2022-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0004_auto_20220304_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='spacing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
