# Generated by Django 3.2.12 on 2022-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0005_auto_20220304_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='picture',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='planting_depth_in_inches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='planting_end_days_to_first_frost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='planting_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='planting_start_days_to_first_frost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='sub_classification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
