# Generated by Django 3.2.12 on 2022-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0006_auto_20220304_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='planting_end_days_to_first_frost',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='planting_start_days_to_first_frost',
        ),
        migrations.AddField(
            model_name='seed',
            name='days_to_transplant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='fall_first_plant_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='fall_last_plant_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='spring_first_plant_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='spring_last_plant_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
