# Generated by Django 3.2.12 on 2022-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0007_auto_20220304_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='fall_first_plant_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='fall_last_plant_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='spring_first_plant_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='spring_last_plant_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
