# Generated by Django 3.2.12 on 2022-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0009_auto_20220304_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='average_days_to_harvest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
