# Generated by Django 3.2.12 on 2022-03-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0010_seed_average_days_to_harvest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='planting_method',
            new_name='start_method',
        ),
    ]
