# Generated by Django 3.2.12 on 2022-03-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0011_rename_planting_method_seed_start_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='days_to_transplant',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='fall_first_plant_date',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='fall_last_plant_date',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='planting_depth_in_inches',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='spacing',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='spring_first_plant_date',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='spring_last_plant_date',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='start_method',
        ),
    ]
